### PR TITLE
writing typedeco annotations for controllers and generating documenta…

### PR DESCRIPTION
**Pull request by Biniyamseid**
…tion  I have generated documentation,

### CODE REVIEW

**Comment by Biniyamseid** [comment]
guys please merge it as fast as possible.

**Review by sami-bre — APPROVED** [review]
I like the doumentation comments : )

**Review by sami-bre — APPROVED** [review]
I like the doumentation comments : )

**Review by sami-bre — APPROVED** [review]
I like the documentation comments. let's merge it

**Pull request merged**
